# The host that we are binding to, defaults to 0.0.0.0
host = "0.0.0.0"
# The port used by our server, defaults to 3000
port = 3000
# A list of domains that our service accepts
whitelist = ["example.org"]
